import {createAction} from '@reduxjs/toolkit';

import {
  Coin,
  CoinsResponseData,
  GlobalMarketData,
} from '../interfaces/response';

const ACTION_TYPES = {
  CRYPTO: {
    FETCH_LIST: 'CRYPTO/FETCH_LIST',
    FETCH_LIST_SUCCESS: 'CRYPTO/FETCH_LIST_SUCCESS',
    FETCH_LIST_FAIL: 'CRYPTO/FETCH_LIST_FAIL',
  },
  USER_PREF: {
    ADD_FAVOURITE: 'USER_PREF/ADD_FAVOURITE',
    DEL_FAVOURITE: 'USER_PREF/DEL_FAVOURITE',
    SET_FAVOURITE: 'USER_PREF/SET_FAVOURITE',
  },
  MARKET: {
    FETCH_LIST: 'MARKET/FETCH_LIST',
    FETCH_LIST_SUCCESS: 'MARKET/FETCH_LIST_SUCCESS',
    FETCH_LIST_FAIL: 'MARKET/FETCH_LIST_FAIL',
  },
  TREND: {
    FETCH_LIST: 'TREND/FETCH_LIST',
    FETCH_LIST_SUCCESS: 'TREND/FETCH_LIST_SUCCESS',
    FETCH_LIST_FAIL: 'TREND/FETCH_LIST_FAIL',
  },
};

const ACTIONS = {
  CRYPTO: {
    FETCH_LIST: createAction(ACTION_TYPES.CRYPTO.FETCH_LIST),
    FETCH_LIST_SUCCESS: createAction<{
      list: CoinsResponseData[];
      index: number;
    }>(ACTION_TYPES.CRYPTO.FETCH_LIST_SUCCESS),
    FETCH_LIST_FAIL: createAction<Error>(ACTION_TYPES.CRYPTO.FETCH_LIST_FAIL),
  },
  USER_PREF: {
    ADD_FAVOURITE: createAction<string[]>(ACTION_TYPES.USER_PREF.ADD_FAVOURITE),
    DEL_FAVOURITE: createAction<string>(ACTION_TYPES.USER_PREF.DEL_FAVOURITE),
    SET_FAVOURITE: createAction<string>(ACTION_TYPES.USER_PREF.SET_FAVOURITE),
  },
  MARKET: {
    FETCH_LIST: createAction(ACTION_TYPES.MARKET.FETCH_LIST),
    FETCH_LIST_SUCCESS: createAction<GlobalMarketData>(
      ACTION_TYPES.MARKET.FETCH_LIST_SUCCESS,
    ),
    FETCH_LIST_FAIL: createAction<Error>(ACTION_TYPES.MARKET.FETCH_LIST_FAIL),
  },
  TREND: {
    FETCH_LIST: createAction(ACTION_TYPES.TREND.FETCH_LIST),
    FETCH_LIST_SUCCESS: createAction<Coin[]>(
      ACTION_TYPES.TREND.FETCH_LIST_SUCCESS,
    ),
    FETCH_LIST_FAIL: createAction<Error>(ACTION_TYPES.TREND.FETCH_LIST_FAIL),
  },
};

export default ACTION_TYPES;

export {ACTION_TYPES, ACTIONS};
